[package]
name = "organize-pipe"
version = "0.1.0"
edition = "2021"

[dependencies]
# Add the dependencies for your new engine here
# For example:
# logos = "0.14.0"
# chumsky = "1.0.0-alpha.6"
# anyhow = "1.0"
# serde_json = "1.0"
# async-trait = "0.1"
