
rules:
  - folders:
      recursive: false
      watch: false
      - path: ... # this folder will not be scanned recursively
        watch: true # this folder will be constantly watched for changes
      - path: ...
        recursive: true
    actions:
      - ...
      - ...
    filters:
      - ...
      - ...
