language: rust

rust:
  - stable

script: | 
  cargo build --verbose &&
  cargo test --verbose

branches:
  only:
    - staging # bors r+
    - trying # bors try
    - master
    - alpha-2.0

cache: cargo

matrix:
  fast_finish: true
  allow_failures:
    - env: NAME='cargo-travis'
  include:
    - env: NAME='cargo-travis'
      before_script:
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
      script:
        - cargo fmt 
        - cargo clippy --verbose
      addons: # required for kcov
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - cmake


