language: rust

rust:
  - stable
  - beta
  - nightly

script: | 
  cargo build --verbose &&
  cargo test --verbose &&
  cargo fmt &&
  cargo clippy --verbose

branches:
  only:
    - staging # bors r+
    - trying # bors try
    - master
    - alpha-2.0

cache: cargo
sudo: required # travis-ci/travis-ci#9061

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
      - before_script:
        - cargo install cargo-kcov
        - rustup component add rustfmt-preview
        - rustup component add rustfmt --toolchain beta-x86_64-unknown-linux-gnu
        - rustup component add clippy-preview

addons: # required for kcov
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

after_success: |
  cargo kcov && bash <(curl -s https://codecov.io/bash)
