language: rust

rust:
  - stable

script: | 
  cargo build --verbose &&
  cargo test --verbose &&
  cargo fmt &&
  cargo clippy --verbose

branches:
  only:
    - staging # bors r+
    - trying # bors try
    - master
    - alpha-2.0

cache: cargo
sudo: required # travis-ci/travis-ci#9061

matrix:
  fast_finish: true
  include:
      - before_script:
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview

addons: # required for kcov
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

