unstable_features = true
indent_style = "Block"
merge_imports = true
reorder_imports = true
brace_style = "SameLineWhere"
max_width = 120
merge_derives = true
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_lit_single_line = false
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true