[package]
name = "organize-core"
version = "0.1.0"
authors = ["KBR9 <cabero96@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.15"
crossbeam-channel = "0.5.0"
regex = "1.4.1"
serde = { version = "1.0.117", features = ["derive"] }
dirs = "3.0.1"
serde_yaml = "0.8.13"
colored = "2.0.0"
sysinfo = "0.15.3"
lazy_static = "1.4.0"
rayon = "1.5"
trash = "1.2.0"
log = "0.4"
toml = "0.5.7"
anyhow = "1.0.34"
serde_json = "1.0.59"
num-traits = "0.2.14"

[dev-dependencies]
serde_test = "1.0.117"
