vars:
  documents: &docs $HOME/Nextcloud/Documents
  downloads: &down $HOME/Downloads
  pictures: &pics $HOME/Nextcloud/Pictures


rules:
  - actions:
      - move: *docs
    filters:
      - extension: 
        - pdf
        - docx
        - odt
        - djvu
        - mobi
        - epub
    folders:
      - *down
      - $HOME
      - $HOME/Code
      - $HOME/Desktop/

  # WALLPAPERS
  - actions:
      - move: 
          to: $HOME/Nextcloud/Pictures/wallpapers
          if_exists: overwrite
    filters:
      - filename:
          contains: unsplash
    folders:
      - *down
      - *pics

  #PICTURES
  - actions:
      - move: *pics
    filters:
      - extension:
        - jpg
        - jpeg
        - svg
    folders:
      - *down

  #KEEP THE DESKTOP CLEAN
  - actions:
      - move: $HOME
    filters:
      - regex: .*
    folders:
      - $HOME/Desktop/

  #PYTHON FILES
  - actions:
      - move: $HOME/Code/Python/
    filters:
      - extension:
        - py
        - pyx
        - pyc
    folders:
      - $HOME
      - *docs
      - *down

  #RUST FILES
  - actions:
      - move: $HOME/Code/Rust/
    filters:
      - extension: rs
    folders:
      - $HOME
      - *docs
      - *down

  #WEBDEV FILES
  - actions:
      - move: $HOME/Code/Web-Development/
    filters:
      - extension:
        - ts
        - tsx
        - js
        - jsx
        - css
        - html
        - scss
    folders:
      - $HOME
      - *docs
      - *down

  #GO FILES
  - actions:
      - move: $HOME/Code/Go/src/
    filters:
      - extension: go
    folders:
      - $HOME
      - *docs
      - *down

  #SHELL FILES
  - actions:
      - move: $HOME/Code/Bash/
    filters:
      - extension: sh
    folders:
      - $HOME
      - *docs
      - *down

  # ALL OTHER DOWNLOADS
  - actions:
      - move: $HOME/Downloads/{extension}
    filters:
      - regex: .*
    folders:
      - *down
