rules:
  - actions:
      rename:
        to: ""
        if_exists: rename # default
        counter_separator: " " # default
      echo: ""
      shell: ""
      delete: true

    filters:
      regex: ".*all.*"
    options:
      watch: true
      hidden_files: false

    folders:
      - path: "/"
        options:
          watch: false
          hidden_files: true