rules:
  - actions:
      rename:
        to: ""
        if_exists: rename # default
        counter_separator: " " # default

    options:
      watch: true

    folders:
      - path: "/home/user/"
        options:
          watch: false
          hidden_files: false