[connections.aws-frankfurt]
type = "sftp"
address = "localhost:10003"
username = "andres_cabero"

[[stage]]
search = 'sftp://aws-frankfurt/homes/andres_cabero/test-dir'
max_depth = 1

[[stage]]
action = "echo"
message = "{{ file.path }}"

[[stage]]
action = "copy"
folder = "/Users/H0UB8WV/Downloads/test-dir"

# [[stage]]
# filter = "empty"
# check = "C:/Users/H0UB8WV/source/repos/organizer/test_data/empty_file.txt"

# [[stage]]
# action = "echo"
# message = "C:/Users/H0UB8WV/source/repos/organizer/test_data/empty_file.txt is empty!"