[connections.aws-frankfurt]
type = "sftp"
address = "127.0.0.1"
port = 10002
username = "andres_cabero"

[[stage]]
search = "/Users/H0UB8WV/Downloads"

# [[stage]]
# select = "first"
# n = 3

[[stage]]
action = "copy"
folder = "/Users/H0UB8WV/Downloads/"
filename = "{{file.stem}}-1.{{file.extension}}"




# [[stage]]
# filter = "empty"
# check = "C:/Users/H0UB8WV/source/repos/organizer/test_data/empty_file.txt"

# [[stage]]
# action = "echo"
# message = "C:/Users/H0UB8WV/source/repos/organizer/test_data/empty_file.txt is empty!"