[connections.aws-frankfurt]
type = "sftp"
address = "127.0.0.1"
port = 10002
username = "andres_cabero"

[[stage]]
search = '/homes/andres_cabero/es-align/out_aligned'
host = "aws-frankfurt"

[[stage]]
search = '/homes/andres_cabero/es-align/out_decoded'
host = "aws-frankfurt"

# [[stage]]
# select = "first"
# n = 2

[[stage]]
action = "copy"
folder = "/Users/H0UB8WV/Downloads/es-align/{{file.parent}}"


# [[stage]]
# filter = "empty"
# check = "C:/Users/H0UB8WV/source/repos/organizer/test_data/empty_file.txt"

# [[stage]]
# action = "echo"
# message = "C:/Users/H0UB8WV/source/repos/organizer/test_data/empty_file.txt is empty!"