[[stage]]
search = "/Users/cabero/Downloads"

[[stage]]
action = "copy"
folder = "/Users/cabero/Downloads/"
filename = "{{file.stem}}-1.{{file.extension}}"


# [[stage]]
# action = "echo"
# message = "{{ input() }}"


# [[stage]]
# filter = "empty"
# check = "C:/Users/H0UB8WV/source/repos/organizer/test_data/empty_file.txt"

# [[stage]]
# action = "echo" 
# message = "C:/Users/H0UB8WV/source/repos/organizer/test_data/empty_file.txt is empty!"